# Generated by Django 3.0.6 on 2020-10-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotargeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='central_point',
            field=models.TextField(null=True, verbose_name='coordinates'),
        ),
    ]
