# Generated by Django 3.0.6 on 2020-10-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotargeting', '0002_auto_20201003_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='under_point',
            field=models.TextField(null=True, verbose_name='under coordinates'),
        ),
    ]
