# Generated by Django 3.0.6 on 2020-10-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotargeting', '0003_point_under_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central_point', models.TextField(null=True, verbose_name='coordinates')),
                ('temp', models.IntegerField()),
            ],
        ),
    ]
