# Generated by Django 3.0.6 on 2020-10-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'Координаты', 'verbose_name_plural': 'Координаты'},
        ),
        migrations.RemoveField(
            model_name='point',
            name='title',
        ),
        migrations.AlterField(
            model_name='point',
            name='coord',
            field=models.TextField(null=True, verbose_name='coordinates'),
        ),
    ]
